classdef eWP < handle
    
    properties ( Access = 'private' )
        panel
        cEdit
        pEdit
    end
    
    properties
        
        constant
        power
    
    end
    
    methods
        
        function obj = eWP(left, buttom, length, height, wS)
            
            obj.constant = 0.747;
            obj.power = 0.993;
            
            obj.panel = uipanel('Title', 'Empty Weight', ...
                'Units', 'pixels', ...
                'Pos', [left, buttom, length, height], ...
                'Parent', wS);
            obj.cEdit = uicontrol('Style', 'edit', ...
                'FontSize', 12, ...
                'String', num2str(obj.constant), ...
                'Position', [5 5 140 20], ...
                'Parent', obj.panel, ...
                'Callback', @obj.ConsCallback);
            uicontrol('Style', 'text', ...
                'Position', [5 30 140 20], ...
                'String', 'Constant', ...
                'FontSize', 12, ...
                'Parent', obj.panel);
            
            obj.cEdit = uicontrol('Style', 'edit', ...
                'FontSize', 12, ...
                'String', num2str(obj.power), ...
                'Position', [150 5 140 20], ...
                'Parent', obj.panel, ...
                'Callback', @obj.PowCallback);
            uicontrol('Style', 'text', ...
                'Position', [150 30 140 20], ...
                'String', 'Power', ...
                'FontSize', 12, ...
                'Parent', obj.panel);
            
        end
        
        function ConsCallback(obj, hObject, eventdata)
            obj.constant = str2double(get(hObject, 'String'));
        end
        
        function PowCallback(obj, hObject, eventdata)
            obj.power = str2double(get(hObject, 'String'));
        end
    end
            
end
